// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefTarget {
    #[prost(message, repeated, tag="1")]
    pub removes: ::prost::alloc::vec::Vec<ref_target::Term>,
    #[prost(message, repeated, tag="2")]
    pub adds: ::prost::alloc::vec::Vec<ref_target::Term>,
}
/// Nested message and enum types in `RefTarget`.
pub mod ref_target {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Term {
        #[prost(bytes="vec", optional, tag="1")]
        pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteRef {
    #[prost(enumeration="RemoteRefState", tag="1")]
    pub state: i32,
    #[prost(message, optional, tag="2")]
    pub target: ::core::option::Option<RefTarget>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteView {
    #[prost(map="string, message", tag="1")]
    pub bookmarks: ::std::collections::HashMap<::prost::alloc::string::String, RemoteRef>,
    #[prost(map="string, message", tag="2")]
    pub tags: ::std::collections::HashMap<::prost::alloc::string::String, RemoteRef>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct View {
    #[prost(bytes="vec", repeated, tag="1")]
    pub head_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(map="string, message", tag="2")]
    pub local_bookmarks: ::std::collections::HashMap<::prost::alloc::string::String, RefTarget>,
    #[prost(map="string, message", tag="3")]
    pub local_tags: ::std::collections::HashMap<::prost::alloc::string::String, RefTarget>,
    #[prost(map="string, message", tag="4")]
    pub remote_views: ::std::collections::HashMap<::prost::alloc::string::String, RemoteView>,
    #[prost(map="string, bytes", tag="5")]
    pub wc_commit_ids: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag="1")]
    pub millis_since_epoch: i64,
    #[prost(int32, tag="2")]
    pub tz_offset: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OperationMetadata {
    #[prost(message, optional, tag="1")]
    pub start_time: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag="2")]
    pub end_time: ::core::option::Option<Timestamp>,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub username: ::prost::alloc::string::String,
    #[prost(bool, tag="7")]
    pub is_snapshot: bool,
    #[prost(map="string, string", tag="6")]
    pub tags: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitPredecessors {
    #[prost(bytes="vec", tag="1")]
    pub commit_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub predecessor_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Operation {
    #[prost(bytes="vec", tag="1")]
    pub view_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub parents: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag="3")]
    pub metadata: ::core::option::Option<OperationMetadata>,
    #[prost(message, repeated, tag="4")]
    pub commit_predecessors: ::prost::alloc::vec::Vec<CommitPredecessors>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RemoteRefState {
    NewUnspecified = 0,
    Tracked = 1,
}
impl RemoteRefState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RemoteRefState::NewUnspecified => "REMOTE_REF_STATE_NEW_UNSPECIFIED",
            RemoteRefState::Tracked => "REMOTE_REF_STATE_TRACKED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REMOTE_REF_STATE_NEW_UNSPECIFIED" => Some(Self::NewUnspecified),
            "REMOTE_REF_STATE_TRACKED" => Some(Self::Tracked),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
